function Mash(){var a=4022871197,b=function(b){b=b.toString();for(var e=0;e<b.length;e++){a+=b.charCodeAt(e);var d=0.02519603282416938*a;a=d>>>0;d-=a;d*=a;a=d>>>0;d-=a;a+=4294967296*d}return 2.3283064365386963E-10*(a>>>0)};b.version="Mash 0.9";return b}
function Alea(){return function(a){var b=0,c=0,e=0,d=1;0==a.length&&(a=[+new Date]);for(var f=Mash(),b=f(" "),c=f(" "),e=f(" "),h=0;h<a.length;h++)b-=f(a[h]),0>b&&(b+=1),c-=f(a[h]),0>c&&(c+=1),e-=f(a[h]),0>e&&(e+=1);var f=null,g=function(){var a=2091639*b+2.3283064365386963E-10*d;b=c;c=e;return e=a-(d=a|0)};g.uint32=function(){return 4294967296*g()};g.fract53=function(){return g()+1.1102230246251565E-16*(2097152*g()|0)};g.version="Alea 0.9";g.args=a;return g}(Array.prototype.slice.call(arguments))}
var _={A:{opacity1:{opacity:1},opacity0:{opacity:0},slideUpAndFade:{top:"-=100",opacity:0}},asterisk:"\u2217",busy:!1,random_sequence_pos:0,setSeed:function(a,b){this.seed=a||+new Date;this.random_sequence_pos=0;var c,e=b||0;this._random=Alea(this.seed);for(c=0;c<e;c++)this.random()},random:function(){this.random_sequence_pos+=1;return this._random()},randomColor:function(a){var b;do b=Math.floor(7*this.random())+1;while(a&&a[b]);return"t"+b},randomCell:function(a,b){if(0===a.length)return $();var c=
$(a[Math.floor(this.random()*a.length)]);if(b(c))return c;var e=a.filter(function(a){return!$(this).is(c)});return this.randomCell(e,b)},findTarget:function(a){var b=[],c=this.teleports,e=this,d=function(k,d){var f=d.coord();if(d.isOutTeleport()&&!d.isInTeleport())return 0<b.length&&b[b.length-1].isInTeleport()&&b.push(d),k;if(d.isInTeleport()){if(a.justTeleported()&&a.parent().coord()==d.coord())return b.push(d),k;var g=c[[f.x,f.y]],h=g[0],n=g[1],m=e.cell(h,n);if(0<b.length&&b[b.length-1].coord()==
m.coord())return b.push(d),k;if(g)return d.isOutTeleport()&&(0<b.length&&b[b.length-1].isInTeleport())&&b.push(d),b.push(d),{x:h-f.x,y:n-f.y}}else return k;return l},f=a.parent(),h=f.x(),g=h,m=f.y(),k=m,n=a.delta(),l=d(n,f);if(0===l.x&&0===l.y)return null;var t=0,r,s;r=this.cell(g+l.x,k+l.y);for(s=r.brick();null===s||0===s.length;){g+=l.x;k+=l.y;r.isColorChanger()&&!a.isUnchangeableType()&&b.push(r);if((s=r.cellDirectionDelta())&&(s.x!==n.x||s.y!==n.y))b.push(r),n=s;l=d(n,r);r=this.cell(g+l.x,k+l.y);
if(h===g+l.x&&m===k+l.y){if(r.isRepoEdgeCell())break;s=null}else s=r.brick();t++}if(0===t)return null;d=this.cell(g,k);if(d.isBoardEdgeCell()&&(g=this.cell(g+l.x,k+l.y),g.isRepoEdgeCell())){if(f.isRepoCell())return null;d=g}return{cell:d,stops:b}},move:function(a,b,c,e){var d=this;c=0===c?0:c||1;e=a.parent();var f=e.width(),h=b.offset(),g=e.offset(),m=h.left-g.left,h=h.top-g.top,k=$.Deferred(),g=Math.abs(m)+Math.abs(h),n=g/f,f=3>n?"linear":"swing",n=100+30*c*n,l=function(){a.resetTopLeft();a.appendTo(b);
var c=b.isRepoCell();!a.age()&&!c?a.age(-new Date):c&&a.age(null);d.event("in",b,a);k.resolve()};d.event("out",e,a);0===c||0==g?l():a.animate({left:m,top:h},n,f,l);return k.promise()},cell:function(a,b){return this.$board.cell(a,b)},clearCellModifiers:function(){var a,b=this.boardCells,c;for(a=b.length-1;0<=a;a--)c=$(b[a]),c.modifier(null)},changeColor:function(a){var b=this,c=$.Deferred(),e=a.type()[1];if(a.isUnchangeableType())return c.resolve(),c.promise();var d=function(){c.resolve()};a.rotate({angle:0,
animateTo:45,duration:200,callback:function(){var c={};c[e]=1;c=b.randomColor(c);a.type(c);a.rotate({animateTo:0,duration:100,callback:d})}});return c.promise()},teleportIn:function(a){var b=$.Deferred();a.teleporting(!0);a.animate(_.A.opacity0,400,function(){b.resolve()});return b.promise()},teleportOut:function(a){var b=$.Deferred();a.animate(_.A.opacity1,200,function(){a.teleporting(!1);a.justTeleported(!0);setTimeout(function(){b.resolve()},100)});return b.promise()},check:function(a,b,c){a=this.cell(a,
b);return a.isBoardCell()&&(a=a.brick())&&!a.hasClass("tr")&&(a.hasClass(c)||a.hasClass("t-"))?a:null},markLetterDone:function(){var a=$($("#word>span")[this.nextLetterIndex]);a.addClass("done-letter");this.nextLetterIndex+=1;var a=a.text(),b=this.word.slice(this.nextLetterIndex);-1===b.indexOf(a)&&this.$board.withLetter(a).each(function(a,b){$(b).letter("")});0===b.length&&this.wordCompleted();return a},letterCount:function(a){var b=this.word.slice(this.nextLetterIndex);return""===b?0:b.split(a).length-
1},findBombVictims:function(a){var b=a.parent();a=b.x();var b=b.y(),c,e,d,f=[];for(e=a-1;e<=a+1;e+=1)for(d=b-1;d<=b+1;d+=1)c=this.cell(e,d),c.isBoardCell()&&(c=c.brick(),0<c.length&&f.push(c));return f},findCandidates:function(a,b){for(var c,e,d,f,h=[a],g=[],m={};0<h.length;)if(c=h.shift())e=c.parent(),d=e.coord(),e=d.x,d=d.y,f=[e,d],m[f]||(m[f]=!0,g.push(c),h.push(this.check(e+1,d,b)),h.push(this.check(e-1,d,b)),h.push(this.check(e,d+1,b)),h.push(this.check(e,d-1,b)));return g},findTypeCandidates:function(a){var b=
[],c=this,e,d,f,h=[a];a={};for(var g={},m=function(a,e){var d=c.cell(a,e),f;d.isBoardCell()&&d.hasBrick()&&(d=d.brick(),f=d.type(),"t-"===f?h.push(d):g[f]||(g[f]=!0,b.push(f)))};0<h.length;)if(e=h.shift())e=e.parent(),d=e.coord(),e=d.x,d=d.y,f=[e,d],a[f]||(a[f]=!0,m(e+1,d),m(e-1,d),m(e,d+1),m(e,d-1));return b},obstacleAsBomb:function(a){var b=a.parent().coord();a=a.delta();b=this.cell(b.x+a.x,b.y+a.y).brick();return 0<b.length&&"tb"===b.type()?b:null},maybeKill:function(a){var b=this,c=a.type(),e=
"tb"===c,d,f=[],h=this.obstacleAsBomb(a);if(e)f=this.findBombVictims(a);else{if(h)return this.maybeKill(h);if("t-"===c)for(var c=this.findTypeCandidates(a),g,h=c.length-1;0<=h;h--){if(d=c[h],d=b.findCandidates(a,d),2<d.length)for(g=d.length-1;0<=g;g--)-1===f.indexOf(d[g])&&f.push(d[g])}else f=this.findCandidates(a,c)}if(2<f.length||e)return this.kill(f).pipe(function(a){return b.postKill(a,e)});a=$.Deferred();a.resolve(0);return a},slideText:function(a,b,c,e,d){var f=this;setTimeout(function(){f._slideText(a,
b,c,e)},(d||20)+10*Math.random())},_pointsNotificationPool:[],createPointsNotification:function(){var a=this._pointsNotificationPool.shift()||$("<p>").addClass("points-notification").addClass("accel");a.css("opacity",1).show();return a},OFFSET0:{left:0,top:0},destroyPointsNotification:function(a){a.offset(_.OFFSET0).detach();this._pointsNotificationPool.push(a)},_slideText:function(a,b,c,e){var d=$.Deferred();e=e||2E3;var f=this,h=this.createPointsNotification().text(a).hide().appendTo($("body"));
h.offset({left:b-h.width()/2,top:c-h.height()/2}).show().animate(_.A.slideUpAndFade,e,function(){f.destroyPointsNotification(h);d.resolve()});return d.promise()},replenishLetter:function(a){var b=this.$board.withLetter(a),b=this.letterCount(a)-b.length,c;for(c=0;c<b;c+=1)this.addRandomLetters(a)},postKill:function(a,b){var c=$.Deferred(),e=3*a[0].width()/4,d=0,f=0,h=a.length,g=[],m=0,k=b?-1*h:Math.pow(h-1,2),n=0,l,t,r,s;for(l=a.length-1;0<=l;l--)t=a[l],r=t.offset(),s=t.letter(),t.isStationary()&&
(n+=1),this.destroyBrick(t),d+=r.left,f+=r.top,""!==s&&g.push(s);d=d/h+e;f=f/h+e;b||(0<g.length&&(m+=Math.pow(g.length+1,2)),0<n&&(m+=Math.pow(n+2,2)),0<m&&(this.addScore(m),this.slideText("+"+m,d+e,f-e)));this.addScore(k);this.slideText((0<k?"+":"")+k,d,f);for(l="";0<g.length;)if(h=this.word[this.nextLetterIndex],h=g.indexOf(h),-1===h&&(h=g.indexOf(_.asterisk)),-1<h)m=this.markLetterDone(),l+=m,g.splice(h,1);else break;""!==l&&this.slideText(l,d-e,f+e);for(l=g.length-1;0<=l;l--)this.replenishLetter(g[l]);
e=a.length-3;if(0<e&&!b)if(this.isWordComplete())if(1===e)this.addRandomWildcard(!1);else for(l=0;l<e-1;l+=1)this.addRandomWildcard(!0);else if(1===e)e=this.word.slice(this.nextLetterIndex),e=e[Math.floor(this.random()*e.length)],this.addRandomLetters(e);else for(l=0;l<e-1;l+=1)this.addRandomLetters(_.asterisk);c.resolve(1);return c.promise()},wordCompleted:function(){this.$board.find(".l:contains("+_.asterisk+")").each(function(a,b){var c=$(b);c.letter("");c.type("t-")})},isLevelCleared:function(){return 0===
this.boardCells.find(".k").not(".tr").length},addScore:function(a){this.setScore(this.levelScore+a)},setScore:function(a){this.levelScore=a;$("#score").text(this.levelScore)},setWord:function(a){this.word=a;var b,c,e=$("#word"),d=a.length;e.empty();for(b=0;b<d;b+=1)c=$("<span>"),c.text(a[b]),b<this.nextLetterIndex&&c.addClass(c.addClass("done-letter")),c.appendTo(e)},isWordComplete:function(){return this.nextLetterIndex>=this.word.length},kill:function(a){var b=this,c=$.Deferred(),e=[];$.each(a,function(a,
c){var h=$.Deferred();c.animate(_.A.opacity0,600,function(){b.event("out",c.parent(),c);h.resolve()});e.push(h.promise())});$.when.apply(window,e).then(function(){c.resolve(a)});return c.promise()},pushOut:function(a){var b,c,e,d,f=this;e=a.replenishDelta();var h=$.Deferred();d=a.brick();0<d.length&&e?(b=a.x(),c=a.y(),b=this.cell(b+e.x,c+e.y),0<b.length?this.pushOut(b).pipe(function(a){return f.move(d,a,0.5)}).pipe(function(){h.resolve(a)}):d.animate(_.A.opacity0,function(){var b=$(this),c=b.letter();
f.destroyBrick(b);""!==c&&f.replenishLetter(c);h.resolve(a)})):h.resolve(a);return h.promise()},handleStopCell:function(a,b){var c=this,e=$.Deferred(),d=b.shift(),f=d.isInTeleport()&&0<b.length&&b[0].isOutTeleport(),h=a.teleporting()?0:1;a.justTeleported(!1);a.teleportBound(!1);this.move(a,d,h).pipe(function(){if(d.isColorChanger())return c.changeColor(a);if(d.isTeleport()){if(a.teleporting())return c.teleportOut(a);if(f)return c.teleportIn(a);d.isInTeleport()&&a.teleportBound(!0);return null}var b=
d.cellDirection();return b?a.changeDirection(b):null}).pipe(function(){0<b.length?c.handleStopCell(a,b).done(function(){e.resolve()}):e.resolve()});return e.promise()},shoot:function(a){var b=a.parent(),c=this.findTarget(a),e=$.Deferred();if(c){var d=this,f=c.stops;this.pushOut(c.cell).pipe(function(b){$.Deferred();-1===f.indexOf(b)&&f.push(b);return d.handleStopCell(a,f)}).pipe(function(){var b=a.parent();b.isRepoCell()&&(b=b.cellDirection(),a.brickDirection(b))}).pipe(function(){return d.replenish(b)}).pipe(function(){return d.maybeKill(a)}).pipe(function(a){return d.proceed(a)}).done(function(a){setTimeout(function(){e.resolve(a)},
0)})}else e.resolve(-1);return e.promise()},cmpBrickAge:function(a,b){return b.age()-a.age()},proceed:function(a){var b=$.Deferred(),c=this,e=[],d=a,f,h;f=this.boardCells.find(".k");for(a=f.length-1;0<=a;a--)h=$(f[a]),h.isStationary()||e.push(h);e.sort(this.cmpBrickAge);var g=function(a){0<a&&(d+=a);m()},m=function(){if(0<e.length){var a=e.shift(),f=a.parent();0<f.length&&f.isBoardCell()?c.shoot(a).done(g):setTimeout(m,0)}else setTimeout(function(){b.resolve(d)},0)};m();return b.promise()},replenish:function(a){var b=
$.Deferred();if(!a.isRepoCell())return b.resolve(),b.promise();var c=this,e,d;d=a.replenishDelta();var f=a.coord();e=this.cell(f.x+d.x,f.y+d.y);d=e.brick();0<d.length?this.move(d,a).done(function(){c.replenish(e).done(function(){setTimeout(function(){b.resolve()},0)})}):this.createBrick(a,null,null,null,null,null,!0).done(function(){b.resolve()});return b.promise()},shrug:function(a){var b=$.Deferred(),c=function(){b.resolve()};a.rotate({angle:0,animateTo:90,duration:200,callback:function(){a.rotate({animateTo:0,
duration:200,callback:c})}});return b.promise()},_brickPool:[],_populateBrickPool:function(){var a=this.$board.dimensions().fieldSize,b;for(b=0;b<a*a;b++)this._brickPool.push(this.$board.newBrick())},createBrick:function(a,b,c,e,d,f,h){b=b||this.randomColor();var g=this,m=$.Deferred();e=e||(a.isRepoCell()?a.cellDirection():"");var k=this._brickPool.shift()||this.$board.newBrick();k.type(b);k.age(d||null);k.brickDirection(e);k.letter(c||"");a.isTeleport()&&(k.justTeleported(f),!f&&(a.isInTeleport()&&
!k.isStationary())&&k.teleportBound(!0));h?(k.css("opacity",0),a.append(k),k.animate(_.A.opacity1,50,function(){m.resolve();g.event("in",a,k)})):(a.append(k),m.resolve(),g.event("in",a,k));return m.promise()},destroyBrick:function(a){a.detach();a.css("opacity",1);a.justTeleported(!1);a.teleportBound(!1);this._brickPool.push(a)},currentSnapName:function(a){return"l"+a+"cur"},prevSnapName:function(a){return"l"+a+"prev"},takeSnapshot:function(){var a=[],b,c,e,d,f=this.$board.find(".k");for(b=this.boardCells.length-
1;0<=b;b--)if(c=$(this.boardCells[b]),d=c.data(),(e=d.modifier)&&!c.hasBrick())c=d.coord,a.push([c.x,c.y,e]);var h,g;for(b=f.length-1;0<=b;b--){e=$(f[b]);g=e.data();c=e.parent();d=c.data();c=d.coord;e=d.modifier;d=g.type;h=g.letter;e=[c.x,c.y,e,d[1],h];d=g.direction;c=g.justTeleported?!0:!1;if(d&&(e.push(d),g=g.age))e.push(g),e.push(c);a.push(e)}f=this.getLevelId();a={level:f,word:this.word,teleports:this.teleports,nextLetterIndex:this.nextLetterIndex,levelScore:this.levelScore,shotCount:this.shotCount,
boardState:a,hints:this.hints,seed:this.seed,sequence_pos:this.random_sequence_pos};b=this.currentSnapName(f);f=this.prevSnapName(f);(g=localStorage.getItem(b))&&localStorage.setItem(f,g);localStorage.setItem(b,JSON.stringify(a));this.updateUndoButton()},restorePrevious:function(){var a=this.getLevelId(),b=this.currentSnapName(a),a=this.prevSnapName(a);localStorage.getItem(b);var c=localStorage.getItem(a);if(c)return localStorage.removeItem(b),localStorage.removeItem(a),localStorage.setItem(b,c),
this.loadSnapshot(c);b=$.Deferred();b.reject();return b.promise()},hasPrevious:function(){var a=this.getLevelId(),a=this.prevSnapName(a);return localStorage.getItem(a)?!0:!1},loadSnapshot:function(a){this.clearBoard();a=JSON.parse(a);this.setSeed(a.seed,a.sequence_pos);this.setScore(a.levelScore);this.shotCount=a.shotCount;this.nextLetterIndex=a.nextLetterIndex;this.setWord(a.word);this.levelSelector.setCurrentLevelId(a.level);var b=a.boardState;this.updateUndoButton();this.loadHints(a.hints);this.setTeleports(a.teleports);
return this.loadBricks(b)},deleteSnapshots:function(){var a=this.getLevelId(),b=this.currentSnapName(a),a=this.prevSnapName(a);localStorage.removeItem(b);localStorage.removeItem(a);this.updateUndoButton()},deleteHints:function(){this.hints.length=0;$(".hint").filter(":not([id])").remove()},clearState:function(){this.deleteSnapshots();this.deleteHints();this.clearCellModifiers()},setHighScore:function(a){this.highScore=a;$("#highScore").text(this.highScore)},saveHighScore:function(){var a=this.getLevelId();
return this.levelScore>this.highScore?(this.setHighScore(this.levelScore),localStorage.setItem("l"+a+"highScore",this.highScore),!0):!1},restoreHighScore:function(){var a=this.getLevelId(),a=localStorage.getItem("l"+a+"highScore");this.setHighScore(parseInt(a)||0)},updateUndoButton:function(){var a=$("#undoMove"),b=$("#resetLevel");this.hasPrevious()?b.is(":visible")&&(b.hide(),a.show()):a.is(":visible")&&(a.hide(),b.show())},resetLevel:function(){this.clearState();return this.setLevelId(this.getLevelId())},
nextLevel:function(){this.setLevelId(this.levelSelector.getNextLevelId())},prevLevel:function(){this.setLevelId(this.levelSelector.getPrevLevelId())},isLastLevel:function(){return this.levelSelector.isLastLevel()},setLevelId:function(a){var b=this;a=this.levelSelector.setCurrentLevelId(a);var c=this.levelSelector.getCurrentLevelIndex();$("#levelLabel").text(c+1);this.deleteHints();this.clearCellModifiers();return this.showMessage("Loading...",_.A.opacity0,300,function(){return b.populate(a).done(function(){b.event("levelLoaded")})})},
center:function(a){var b=a.offset();a=a.width()/2;return{x:b.left+a,y:b.top+a}},calcLevelBonus:function(){var a=96+Math.min(4*this.shotCount,900),b=this.$board.find(".tb"),c=Math.pow(b.length+2,2),e=c*b.length,d=this.$board.find(".t-"),f=Math.pow(d.length+1,2),h=f*d.length,g=this.$board.find(".tr"),m=Math.pow(g.length+6,2),k=m*g.length,n,l;for(n=b.length-1;0<=n;n--)l=$(b[n]),l=this.center(l),this.slideText("+"+c,l.x,l.y);for(n=d.length-1;0<=n;n--)l=$(d[n]),l=this.center(l),this.slideText("+"+f,l.x,
l.y);for(n=g.length-1;0<=n;n--)l=$(g[n]),l=this.center(l),this.slideText("+"+m,l.x,l.y);return a+e+h+k},blockUI:function(){this.busy=!0},unblockUI:function(){this.busy=!1},updateHintPositions:function(){$(".hint").filter(".updateHintPos").each(function(){var a=$(this),b=a.data("setPos");b||console.warn("not set pos",a);b()})},setup:function(){var a=this,b=function(b){a.updateHintPositions()};$(window).on("resize",b);var c=function(a){$("#overlay").find(".overlayWidget:visible").hide();$(".uiHint").hide();
$("#overlay").hide();$("#transparentOverlay").hide()},e=function(b){if(!a.busy){var c=$("#transparentOverlay"),e=$("#overlay");b=$("#"+b);c.show();e.show();b.show()}},d=function(){e("levelsContainer")};a.levelSelector.onLevelSelected=function(b){c();a.setLevelId(b.id)};var f=function(){e("confirmResetContainer")};$("#confirmResetYes").on(this.buttonEvent,function(){c();a.resetLevel()});$("#confirmResetNo").on(this.buttonEvent,function(){c()});$("#resetLevel").on(this.buttonEvent,f);var h=function(){!a.busy&&
a.hasPrevious()&&a.showMessage("Loading...",_.A.opacity0,300,function(){return a.restorePrevious().done(function(){a.event("levelLoaded")})})};$("#undoMove").on(this.buttonEvent,h);var g=function(b,c,e){var d=$("#"+b),f=$("#"+c);d.data("setPos",function(){a.position(d,e?a.calcPositionTop(f,d):a.calcPositionBottom(f,d),d)})};g("hintLevelButton","levelLabelContainer",!1);g("hintUndoButton","undoButtonContainer",!0);g("hintScore","score",!0);g("hintShowInfo","showInfoContainer",!0);g=function(){a.busy||
(b(),$(".uiHint").show(),e("rulesContainer"))};$("#showHowToPlay").on(this.buttonEvent,g);var m={27:c,s82:f,78:function(){c();a.nextLevel()},80:function(){c();a.prevLevel()},37:function(){$("#selectLevelWidget").is(":visible")&&a.levelSelector.pageLeft()},39:function(){$("#selectLevelWidget").is(":visible")&&a.levelSelector.pageRight()},76:d,72:g,s191:g,8:h};$("body").keyup(function(a){(a=m[(a.shiftKey?"s":"")+(a.ctrlKey?"c":"")+(a.metaKey?"m":"")+a.keyCode])&&a()});$(".closeButton").on(this.buttonEvent,
c);$("#selectLevel").on(this.buttonEvent,d);this._populateBrickPool();this.repoEdgeCells.on(this.shootEvent,function(){if(!a.busy){var b=$(this).brick();0<b.length&&(a.blockUI(),a.shoot(b).pipe(function(c){var d=$.Deferred();-1===c?a.shrug(b).then(function(){a.unblockUI();d.reject()}):d.resolve(c);return d.promise()}).pipe(function(b){var c=$.Deferred(),d=a.isLevelCleared();a.shotCount+=1;if(1<b){var e,k,f,g=Math.pow(b+1,2),h;for(e=0;e<b-1;e++)if(f=a.addRandomWildcard(!0,"tb"))a.addScore(g),k=a.center(f),
d?(h=f.width()/2,f=k.x+h,k=k.y-h):(f=k.x,k=k.y),a.slideText("+"+g,f,k)}d?c.resolve():(a.takeSnapshot(),a.unblockUI(),c.reject());return c.promise()}).pipe(function(){var b=$.Deferred();a.event("levelCleared");a.clearState();if(a.isWordComplete()){var c=a.calcLevelBonus();a.addScore(c);if(a.saveHighScore()){var d=$("#hintTop").clone().attr("id",null);d.find(".hint-text").text("High score!");setTimeout(function(){d.appendTo($("body"));a.position(d,a.calcPositionTop($("#score"),d));d.show()},20)}a.slideMessage("Solved! +"+
c).done(function(){d&&d.animate(_.A.opacity0,500,function(){d.remove()});a.isLastLevel()?a.slideMessage("No more levels").done(function(){b.resolve()}):b.resolve()})}else a.slideMessage("Word is not complete, try again").done(function(){a.unblockUI();b.reject();a.resetLevel()});return b.promise()}).pipe(function(){a.unblockUI();a.nextLevel()}))}})},slideMessage:function(a){return this.showMessage(a,_.A.slideUpAndFade,2E3)},_infoNotificationPool:[],createInfoNotification:function(){var a=this._infoNotificationPool.shift()||
$("<p>").addClass("info-notification").addClass("accel");a.css("opacity",1);return a},destroyInfoNotification:function(a){a.detach();this._infoNotificationPool.push(a)},showMessage:function(a,b,c,e){var d=this.$board,f=this;d.offset();d.width();d.height();var h=$("#overlay");f.blockUI();h.show();var g=this.createInfoNotification();g.text(a).appendTo($("#overlayContent"));var m=$.Deferred(),k=function(a){g.animate(b,c,function(){f.destroyInfoNotification(g);h.hide();f.unblockUI();m.resolve(a)})};e?
setTimeout(function(){e().always(k)},20):k();return m.promise()},loadBricks:function(a){var b=this.$board,c=b.parent(),e=this,d=$.Deferred(),f=[];b.detach();$.each(a,function(a,b){var c=b[0],d=b[1],n=b[2],l=b[3],t=b[4],r=b[5],s=b[6],x=b[7];"*"===t&&(t=_.asterisk);n&&e.cell(c,d).modifier(n);l&&(l="?"===l?e.randomColor():"t"+l,f.push(e.createBrick(e.cell(c,d),l,t,r,s,x)))});$.when.apply(window,f).then(function(){c.append(b);d.resolve()});return d.promise()},loadWord:function(a){var b=$.Deferred();a||
(a="");this.setWord(a.toUpperCase());for(a=this.word.length-1;0<=a;a--)this.replenishLetter(this.word[a]);b.resolve();return b.promise()},hints:[],loadHints:function(a){var b,c,e,d=$.Deferred();this.deleteHints();for(b=a.length-1;0<=b;b--)c=a[b],e={},$.extend(!0,e,c),(c=this.createHint(e))&&this.hints.push(e);d.resolve();return d.promise()},setTeleports:function(a){this.teleports=a},calcPositionRight:function(a,b){var c=a.offset(),e=c.top+(a.height()-b.height())/2,c=c.left+a.width();return{top:e,
left:c}},calcPositionLeft:function(a,b){var c=a.offset(),e=c.top+(a.height()-b.height())/2,c=c.left-b.width();return{top:e,left:c}},calcPositionTop:function(a,b){(!a||0===a.length)&&console.log("- Can't position ",b);(!b||0===b.length)&&console.log("* Can't position ",b);var c=a.offset(),e=c.top-b.height(),c=c.left+(a.width()-b.width())/2;return{top:e,left:c}},calcPositionBottom:function(a,b){var c=a.offset(),e=c.top+a.height(),c=c.left+(a.width()-b.width())/2;return{top:e,left:c}},position:function(a,
b){var c=a.offset();(2<Math.abs(c.top-b.top)||2<Math.abs(c.left-b.left))&&a.css(b)},calcLevelHintPosition:function(a){var b=this.$board.dimensions(),c=this.cell(b.repoSize,0),e=this.cell(b.fieldSize+b.repoSize,b.repoSize),b=c.width()*b.fieldSize;a.width()>b&&a.width(b);c=c.offset();b=e.offset();e=(c.left+b.left)/2;c=(c.top+b.top)/2-a.height()/2;a=e-a.width()/2;return{top:c,left:a}},createHint:function(a){var b=this,c,e,d,f=this.$board;if(a.hide.fired)return!1;var h=function(k){var f;"top"===a.show.where?
(f=$("#levelHintContainer").clone().addClass("updateHintPos").addClass("accel").attr("id",null),f.find(".hint-text").text(a.text),k=function(){b.position(f,b.calcLevelHintPosition(f))}):"word"===a.show.where?(f=$("#hintBottom").clone().addClass("updateHintPos").addClass("accel").attr("id",null),f.find(".hint-text").text(a.text),k=function(){var a=$("#word"),a=a.is(":visible")?b.calcPositionBottom(a,f):{top:0,left:-f.width()};b.position(f,a)}):(c=b.cell(k[0],k[1]),c.hasClass("ru")?(e="#hintBottom",
d=b.calcPositionBottom):c.hasClass("rl")?(e="#hintLeft",d=b.calcPositionRight):c.hasClass("rr")?(e="#hintRight",d=b.calcPositionLeft):(e="#hintTop",d=b.calcPositionTop),f=$(e).clone().addClass("updateHintPos").attr("id",null),f.find(".hint-text").text(a.text),k=function(){b.position(f,d(c,f))});f.data("setPos",k);f.appendTo($("body"));return f},g=function(a,b){if(!b)return!1;var c=!1;$.each(b,function(b,d){d[0]===a[0]&&d[1]===a[1]&&(c=!0);return!c});return c},m=function(a,b,c){return function(d,e){if({levelLoaded:1,
levelCleared:1}[d.type])return!0;var k=e.cell.x(),f=e.cell.y(),k=e.cell&&0<e.cell.length&&(!a||k===a[0]&&f===a[1]&&!g([k,f],e.excludedCells)),f=!b||e.brickType&&e.brickType===b,l=!c||e.letter&&(e.letter===c||e.letter===_.asterisk&&"*"===c);return k&&f&&l}},k=a.show.event,n=a.hide.event,l=m(k.cell,k.brickType,k.letter),t=m(n.cell,n.brickType,n.letter),r=function(b){var c,d,e;a.show.fired=!0;a.show.cell?c=a.show.cell:a.show.event.cell?c=a.show.event.cell:b&&(b.cell&&0<b.cell.length)&&(c=[b.cell.x(),
b.cell.y()],a.show.event.cell=c);d=h(c);e=d.data("setPos");f.unbind(k.type,s);f.bind(n.type,function(b,c){t(b,c)&&(a.hide.fired=!0,d.animate(_.A.opacity0,500,function(){d.remove()}))});setTimeout(function(){e();d.show()},50)},s=function(a,b){l(a,b)&&r(b)};a.show.fired?r():this.$board.bind(k.type,s);return!0},addRandomLetters:function(a){var b,c,e=$.Deferred(),d=a.length,f=this.repoCells,h=function(a){return!a.brick().letter()};for(b=0;b<d;b+=1)c=this.randomCell(f,h),c=c.brick(),c.letter(a[b]);e.resolve();
return e.promise()},addRandomWildcard:function(a,b){var c,e=this,d=b||"t-";c=a?this.repoEdgeCells.filter(function(){var a=$(this).brick();return null!==e.findTarget(a)}):this.repoCells;c=this.randomCell(c,function(a){a=a.brick();return!a.hasClass(d)&&!a.hasClass("t-")&&0<a.length});return 0<c.length?(c=c.brick(),c.type(d),c):a?this.addRandomWildcard(!a,d):null},clearBoard:function(){var a=this;$(".k").each(function(){a.destroyBrick($(this))})},loadLevel:function(a){var b=this;this.clearBoard();var c=
$.Deferred();a=this.levelSelector.getLevel(a);this.setScore(0);this.nextLetterIndex=this.shotCount=0;this.loadHints(a.hints);this.setTeleports(a.teleports);a=[this.loadBricks(a.layout),this.loadWord(a.word)];$.when.apply(window,a).then(function(){b.setSeed();b.takeSnapshot();c.resolve()});return c.promise()},populate:function(a){var b=this.currentSnapName(a),b=localStorage.getItem(b);this.restoreHighScore();if(b)try{return this.loadSnapshot(b)}catch(c){return console.log("Failed to load snapshot for level "+
a,c),this.loadLevel(a)}else return this.loadLevel(a)},levelScore:0,hishScore:0,shotCount:0,getLevelId:function(){return this.levelSelector.getCurrentLevelId()},setStyle:function(a){$("link").each(function(){var b=$(this),c=b.attr("title");c&&(c===a?(b.attr("rel","stylesheet"),b.attr("disabled",!1)):(b.attr("rel","alternate stylesheet"),b.attr("disabled",!0)))})},parseOptions:function(a){var b=window.location.hash.substring(1).split(";");$.each(b,function(b,e){var d=e.split("=",2);1===d.length?d[0]&&
(a[d[0]]=!0):2===d.length&&d[0]&&({no:1,"false":1,0:1}[d[1].toLowerCase()]?a[d[0]]=!1:a[d[0]]=d[1])});return a},levelSelector:{onLevelSelected:function(a){console.log("Level selected: "+a.id)},create:function(a,b,c){function e(a,b,c,d){if(!a)return $("<div>").addClass("levelThumb").addClass("toolButton");c=a?a.id:null;a=$(a.thumb);a.data("levelId",c);a.data("levelIndex",b);return a}function d(){r(n-1)}function f(){r(n+1)}function h(b){var c=g[b];console.log("Level index for ",b,"is",c);c?(m=b,k=c):
(k=0,m=a.levels[k].id);localStorage.setItem("level",m);r(Math.floor(c/l));return m}var g={};$.each(a.levels,function(a,b){g[b.id]=a});var m=null,k,n,l=9;this.pageLeft=d;this.pageRight=f;this.setCurrentLevelId=h;var t=function(){if(null===m){var a=localStorage.getItem("level");return h(a)}return m};this.getCurrentLevelId=t;this.getCurrentLevelIndex=function(){return k};this.getNextLevelId=function(){var b=g[t()];return(b=a.levels[b+1])?b.id:a.levels[0].id};this.isLastLevel=function(){var b=g[t()];
return!a.levels[b+1]};this.getPrevLevelId=function(){var b=g[t()];return(b=a.levels[b-1])?b.id:a.levels[a.levels.length-1].id};this.getLevel=function(b){return a.levels[g[b]]};var r=function(a){0>a?a=s-1:a>=s&&(a=0);var b=a*l,c=b+l;n=a;var d=1,e,f;for($("#selectLevelWidget").find(".thumbHolder").find(".levelThumb").detach();b<c;b++)e=x[b],e.removeClass("levelThumbCurrent"),b===k&&e.addClass("levelThumbCurrent"),f=localStorage.getItem("l"+e.data("levelId")+"highScore"),e.find(".thumb-highScore").text(parseInt(f)||
0),f=$("#thumbHolder"+d),f.append(e),d+=1;$("#pagePositionContainer").find("div.activePagePosition").removeClass("activePagePosition");$("#pagePositionIndicator"+a).addClass("activePagePosition")},s=function(){var b=Math.ceil(a.levels.length/l),c=$("#pagePositionContainer"),d;for(d=0;d<b;d++)$("<div>").attr("id","pagePositionIndicator"+d).addClass("pagePositionIndicator").appendTo(c).on(_.buttonEvent,function(a){return function(){r(a)}}(d));return b}(),x=function(){var b,c=a.levels,d=c.length,k,f=
{};console.log("Levels count:",d);for(b=0;b<d;b++)k=e(c[b],b),f[b]=k;for(;b<s*l;)k=e(c[b]),f[b]=k,b+=1;return f}(),A=this;$("#btnScrollLevelsLeft").on(_.buttonEvent,function(){d()});$("#btnScrollLevelsRight").on(_.buttonEvent,function(){f()});$("#selectLevelWidget").delegate(".thumb-board",_.buttonEvent,function(){var b=$(this).parent().data("levelIndex");A.onLevelSelected(a.levels[b])})}},allHintsFired:function(){var a=!0;if(0===this.hints.length)return!0;$.each(this.hints,function(b,c){return c.hide.fired?
!0:a=!1});return a},event:function(a,b,c,e){this.allHintsFired()||this.$board.trigger(a,{cell:b,brickType:c?c.type():void 0,letter:e})},main:function(a,b){this.setSeed();var c=window.devicePixelRatio||1;1!==c&&$("head").append('<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale='+1/c+'"/>');c={asterisk:"\u2217"};navigator&&navigator.userAgent&&-1<navigator.userAgent.indexOf("hpwOS")&&(c.asterisk="*");Modernizr.touch?(console.log("Touch events are supported"),this.buttonEvent=
"touchend",this.shootEvent="touchstart",$("#keyboardShortcutsInfo").hide(),$(function(){var a=$("#rulesContainer");$(document).bind("touchmove",function(b){a.is(":visible")||b.preventDefault()})})):(console.log("Touch events are NOT supported"),this.shootEvent=this.buttonEvent="click");c=this.parseOptions(c);console.log("Options: "+c);this.asterisk=c.asterisk;this.$board=$("#board").initBoard(a,b);this.repoEdgeCells=this.$board.repoEdgeCells();this.repoCells=this.$board.repoCells();this.boardCells=
this.$board.boardCells();this.boardCells.on(this.shootEvent,function(a){a=$(this);var b=a.coord(),c=[b.x,b.y].toString(),g=[];a.isInTeleport()&&(b=e.teleports[c])&&g.push(e.cell(b[0],b[1]));a.isOutTeleport()&&$.each(e.teleports,function(a,b){if(b.toString()===c){var d=a.split(",");g.push(e.cell(parseInt(d[0]),parseInt(d[1])))}});$.each(g,function(a,b){b.rotate({angle:0,animateTo:360,duration:600})})});var e=this;this.showMessage("Preparing...",_.A.opacity0,0,function(){var c=$.Deferred();e.setup();
$.getJSON("levels.json",function(f){e.levels=f.levels;var h=f.appDisplayName;h&&$("#rulesAppName").text(h);var g=f.nag;g&&g.message&&($("#nagText").text(g.message),$("#rulesNag").text(g.message),$("#nagContainer").show(),$("#rulesNagContainer").show(),g.url&&($("#rulesNag").attr("href",g.url),$("#nagText").on(e.buttonEvent,function(){window.open(g.url)})));e.levelSelector.create(f,a,b);f=e.levelSelector.getCurrentLevelId();c.resolve(f)});return c.promise()}).pipe(function(a){e.setLevelId(a).done(function(){e.$board.animate(_.A.opacity1,
500);$("#levelLabelContainer").show();$("#scoreContainer").show();$("#showInfoContainer").show();$("#undoButtonContainer").show();e.updateUndoButton();e.updateHintPositions()})})}};
(function(a){var b={rd:"du",ru:"dd",rr:"dl",rl:"dr"},c={dl:{x:-1,y:0},dr:{x:1,y:0},du:{x:0,y:-1},dd:{x:0,y:1},d0:{x:0,y:0}},e={rd:{x:0,y:1},ru:{x:0,y:-1},rr:{x:1,y:0},rl:{x:-1,y:0}},d={top:"",left:""},f={tp:!0,tp_in:!0,tp_out:!0},h={tp:!0,tp_in:!0},g={tp:!0,tp_out:!0},m={_default:function(){return a("#board")},newBrick:function(){return a("<div/>").addClass("k").addClass("accel").append(a("<div/>").addClass("quad-content")).append(a("<div/>").addClass("quad-extra"))},type:function(a){if(void 0!==
a){var b=this.data("type"),c=this.parent();b&&this.removeClass(b);this.addClass(a);this.data("type",a);c&&_.event("in",c,this)}return this.data("type")},age:function(a){void 0!==a&&this.data("age",a);return this.data("age")},isUnchangeableType:function(){var a=this.data("type")[1];return"-"===a||"b"===a||"r"===a},content:function(){return this.children(":first")},contentExtra:function(){return this.children(":last")},brickDirection:function(a){var b=this.content();if(void 0!==a){var c=this.data("direction");
c&&b.removeClass(c);b.addClass(a);this.data("direction",a)}return this.data("direction")},changeDirection:function(b){var d=a.Deferred(),e=this,f=function(){e.brickDirection(b);e.rotate({angle:0,animateTo:0,duration:0});d.resolve()},g=this.delta(),h=c[b],g=90*(g.x*h.y-g.y*h.x+g.x*h.x*(1-g.x*h.x)+g.y*h.y*(1-g.y*h.y));0===g?d.resolve():this.rotate({angle:0,animateTo:g,duration:200,callback:f});return d.promise()},isStationary:function(){return!this.brickDirection()},letter:function(a){if(void 0===a)return this.data("letter");
var b=this.parent();this.content().text(a);this.data("letter",a);a?(this.addClass("l"),_.event("in",b,this,a)):(this.removeClass("l"),_.event("out",b,this,a));return a},delta:function(){var a=this.brickDirection();return c[a]||c.d0},resetTopLeft:function(){this.css(d)},justTeleported:function(a){if(void 0===a)return this.data("justTeleported");this.data("justTeleported",a);return a},teleportBound:function(a){if(void 0===a)return this.data("teleportBound");this.data("teleportBound",a);a?this.contentExtra().addClass("teleport-bound"):
this.contentExtra().removeClass("teleport-bound");return a},teleporting:function(a){if(void 0===a)return this.data("teleporting");this.data("teleporting",a);return a},isColorChanger:function(){return"cc"===this.data("modifier")},isTeleport:function(){return f[this.data("modifier")]?!0:!1},isInTeleport:function(){return h[this.data("modifier")]?!0:!1},isOutTeleport:function(){return g[this.data("modifier")]?!0:!1},modifier:function(a){var b=this.data("modifier");if(void 0===a)return b;b&&this.removeClass(b).removeClass("accel").data("modifier",
null);this.addClass(a).data("modifier",a);this.isTeleport()&&this.addClass("accel");return a},coord:function(){return this.data("coord")},x:function(){var a=this.data("coord");return a?a.x:void 0},y:function(){var a=this.data("coord");return a?a.y:void 0},brick:function(){return this.children(":first")},hasBrick:function(a){return 0===this.brick().length?!1:!0},isRepoCell:function(){return this.hasClass("r")},isRepoEdgeCell:function(){return this.hasClass("re")},isBoardEdgeCell:function(){return this.hasClass("be")},
isBoardCell:function(){return this.hasClass("b")},cellDirection:function(){return b[this.data("modifier")]||""},cellDirectionDelta:function(){var a=this.cellDirection();return a?c[a]:null},replenishDelta:function(){return e[this.data("modifier")]||null},initBoard:function(b,c){var d=b+c,e=2*b+c,f=[],g=a("#board"),h,m,y,p,z;for(h=0;h<e;h++){y=a("<tr/>");z=[];for(m=0;m<e;m++){p=m;var q=h,u=[],w=void 0,v=a("<td/>").data("coord",{x:p,y:q});p>=b&&p<d&&q>=b&&q<d?(u.push("b"),((p===b||p===d-1)&&q>=b&&q<
d||(q===b||q===d-1)&&p>=b&&p<d)&&u.push("be")):(((p===b-1||p===d)&&q>b-1&&q<d||(q===b-1||q===d)&&p>b-1&&p<d)&&u.push("re"),p>=b&&(p<d&&q<b&&0<=q)&&(u.push("r"),u.push("ru"),v.data("modifier","ru"),w=!0),p>=b&&(p<d&&q>=d&&q<e)&&(u.push("r"),u.push("rd"),v.data("modifier","rd"),w=!0),p<b&&(0<=p&&q>=b&&q<d)&&(u.push("r"),u.push("rl"),v.data("modifier","rl"),w=!0),p>=d&&(p<e&&q>=b&&q<d)&&(u.push("r"),u.push("rr"),v.data("modifier","rr"),w=!0),w||u.push("x"),0<=p&&p<b&&0<=q&&q<b?u.push("tlc"):p>=d&&p<
e&&0<=q&&q<b?u.push("trc"):0<=p&&p<b&&q>=d&&q<e?u.push("blc"):p>=d&&(p<e&&q>=d&&q<e)&&u.push("brc"));v.addClass(u.join(" "));p=v;p.appendTo(y);z.push(p)}y.appendTo(g);f.push(z)}a(".tlc").slice(1).remove();a(".tlc").attr({colspan:b,rowspan:b}).append(a("#levelLabelContainer"));a(".trc").slice(1).remove();a(".trc").attr({colspan:b,rowspan:b}).append(a("#scoreContainer"));a(".brc").slice(1).remove();a(".brc").attr({colspan:b,rowspan:b}).append(a("#showInfoContainer"));a(".blc").slice(1).remove();a(".blc").attr({colspan:b,
rowspan:b}).append(a("#undoButtonContainer"));this.data("dimensions",{repoSize:b,fieldSize:c});this.data("cells",f);return this},cell:function(b,c){var d=this.data("cells")[c];if(!d)return a();d=d[b];return!d?a():d},dimensions:function(){return this.data("dimensions")},withLetter:function(a){return this.find(".l:contains("+a+")")},repoEdgeCells:function(){return this.find(".re")},repoCells:function(){return this.find(".r")},boardCells:function(){return this.find(".b")}};Object.keys(m).forEach(function(b){a.fn[b]&&
console.error("Name conflict (method already exists in jquery): "+b);a.fn[b]=m[b]})})(jQuery);$(function(){_.main(3,10)});
