function Mash(){var a=4022871197,b=function(b){b=b.toString();for(var d=0;d<b.length;d++){a+=b.charCodeAt(d);var e=0.02519603282416938*a;a=e>>>0;e-=a;e*=a;a=e>>>0;e-=a;a+=4294967296*e}return 2.3283064365386963E-10*(a>>>0)};b.version="Mash 0.9";return b}
function Alea(){return function(a){var b=0,c=0,d=0,e=1;0==a.length&&(a=[+new Date]);for(var f=Mash(),b=f(" "),c=f(" "),d=f(" "),g=0;g<a.length;g++)b-=f(a[g]),0>b&&(b+=1),c-=f(a[g]),0>c&&(c+=1),d-=f(a[g]),0>d&&(d+=1);var f=null,h=function(){var a=2091639*b+2.3283064365386963E-10*e;b=c;c=d;return d=a-(e=a|0)};h.uint32=function(){return 4294967296*h()};h.fract53=function(){return h()+1.1102230246251565E-16*(2097152*h()|0)};h.version="Alea 0.9";h.args=a;return h}(Array.prototype.slice.call(arguments))}
var _={A:{opacity1:{opacity:1},opacity0:{opacity:0},slideUpAndFade:{top:"-=100",opacity:0}},asterisk:"\u2217",busy:!1,random_sequence_pos:0,setSeed:function(a,b){this.seed=a||+new Date;this.random_sequence_pos=0;var c,d=b||0;this._random=Alea(this.seed);for(c=0;c<d;c++)this.random()},random:function(){this.random_sequence_pos+=1;return this._random()},randomColor:function(a){var b;do b=Math.floor(7*this.random())+1;while(a&&a[b]);return"t"+b},randomCell:function(a,b){if(0===a.length)return $();var c=
$(a[Math.floor(this.random()*a.length)]);if(b(c))return c;var d=a.filter(function(a){return!$(this).is(c)});return this.randomCell(d,b)},findTarget:function(a){var b=a.parent(),c=b._("x"),d=c,e=b._("y"),f=e,g=a._("delta");if(0===g.x&&0===g.y)return null;var h=0,k,p=[],m;k=this.cell(d+g.x,f+g.y);for(m=k._("brick");null===m||0===m.length;){d+=g.x;f+=g.y;k._("isColorChanger")&&!a._("isUnchangeableType")&&p.push(k);if((m=k._("cellDirectionDelta"))&&(m.x!==g.x||m.y!==g.y))p.push(k),g=m;k=this.cell(d+g.x,
f+g.y);if(c===d+g.x&&e===f+g.y){if(k.hasClass("re"))break;m=null}else m=k._("brick");h++}if(0===h)return null;a=this.cell(d,f);if(a.hasClass("be")&&(d=this.cell(d+g.x,f+g.y),d.hasClass("re"))){if(b.hasClass("r"))return null;a=d}return{cell:a,stops:p}},move:function(a,b,c,d){var e=this,f=c||1;c=a.parent();var g=c.width(),h=b.offset(),k=c.offset();d=h.left-k.left;var h=h.top-k.top,p=$.Deferred(),k=(Math.abs(d)+Math.abs(h))/g,g=3>k?"linear":"swing",f=100+30*f*k;e.event("out",c,a);a.animate({left:d,top:h},
f,g,function(){a._("resetTopLeft");a.appendTo(b);!a.data("age")&&!b.hasClass("r")?a.data("age",-new Date):b.hasClass("r")&&a.data("age",null);e.event("in",b,a);p.resolve()});return p.promise()},cell:function(a,b){return this.$board._("cell",a,b)},clearCellModifiers:function(){var a,b=this.boardCells,c,d;for(a=b.length-1;0<=a;a--)c=$(b[a]),(d=c.data("modifier"))&&c.removeClass(d).data("modifier",null)},changeColor:function(a){var b=this,c=$.Deferred(),d=a._("type")[1];if(a._("isUnchangeableType"))return c.resolve(),
c.promise();var e=function(){c.resolve()};a.rotate({angle:0,animateTo:45,duration:200,callback:function(){var c={};c[d]=1;c=b.randomColor(c);a._("type",c);a.rotate({animateTo:0,duration:100,callback:e})}});return c.promise()},check:function(a,b,c){a=this.cell(a,b);return a.hasClass("b")&&(a=a._("brick"))&&!a.hasClass("tr")&&(a.hasClass(c)||a.hasClass("t-"))?a:null},markLetterDone:function(){var a=$($("#word>span")[this.nextLetterIndex]);a.addClass("done-letter");this.nextLetterIndex+=1;var a=a.text(),
b=this.word.slice(this.nextLetterIndex);-1===b.indexOf(a)&&this.$board._("withLetter",a).each(function(a,b){$(b)._("letter","")});0===b.length&&this.wordCompleted();return a},letterCount:function(a){var b=this.word.slice(this.nextLetterIndex);return""===b?0:b.split(a).length-1},findBombVictims:function(a){var b=a.parent();a=b._("x");var b=b._("y"),c,d,e,f=[];for(d=a-1;d<=a+1;d+=1)for(e=b-1;e<=b+1;e+=1)c=this.cell(d,e),c.hasClass("b")&&(c=c._("brick"),0<c.length&&f.push(c));return f},findCandidates:function(a,
b){for(var c,d,e,f,g=[a],h=[],k={};0<g.length;)if(c=g.shift())d=c.parent(),e=d._("coord"),d=e.x,e=e.y,f=[d,e],k[f]||(k[f]=!0,h.push(c),g.push(this.check(d+1,e,b)),g.push(this.check(d-1,e,b)),g.push(this.check(d,e+1,b)),g.push(this.check(d,e-1,b)));return h},findTypeCandidates:function(a){var b=[],c=this,d,e,f,g=[a];a={};for(var h={},k=function(a,d){var e=c.cell(a,d),f;e.hasClass("b")&&e._("hasBrick")&&(e=e._("brick"),f=e._("type"),"t-"===f?g.push(e):h[f]||(h[f]=!0,b.push(f)))};0<g.length;)if(d=g.shift())d=
d.parent(),e=d._("coord"),d=e.x,e=e.y,f=[d,e],a[f]||(a[f]=!0,k(d+1,e),k(d-1,e),k(d,e+1),k(d,e-1));return b},obstacleAsBomb:function(a){var b=a.parent()._("coord");a=a._("delta");b=this.cell(b.x+a.x,b.y+a.y)._("brick");return 0<b.length&&"tb"===b._("type")?b:null},maybeKill:function(a){var b=this,c=a._("type"),d="tb"===c,e,f=[],g=this.obstacleAsBomb(a);if(d)f=this.findBombVictims(a);else{if(g)return this.maybeKill(g);if("t-"===c)for(var c=this.findTypeCandidates(a),h,g=c.length-1;0<=g;g--){if(e=c[g],
e=b.findCandidates(a,e),2<e.length)for(h=e.length-1;0<=h;h--)-1===f.indexOf(e[h])&&f.push(e[h])}else f=this.findCandidates(a,c)}if(2<f.length||d)return this.kill(f).pipe(function(a){return b.postKill(a,d)});a=$.Deferred();a.resolve(0);return a},slideText:function(a,b,c,d,e){var f=this;setTimeout(function(){f._slideText(a,b,c,d)},(e||20)+10*Math.random())},_pointsNotificationPool:[],createPointsNotification:function(){var a=this._pointsNotificationPool.shift()||$("<p>").addClass("points-notification").addClass("accel");
a.css("opacity",1).show();return a},OFFSET0:{left:0,top:0},destroyPointsNotification:function(a){a.offset(_.OFFSET0).detach();this._pointsNotificationPool.push(a)},_slideText:function(a,b,c,d){var e=$.Deferred();d=d||2E3;var f=this,g=this.createPointsNotification().text(a).hide().appendTo($("body"));g.offset({left:b-g.width()/2,top:c-g.height()/2}).show().animate(_.A.slideUpAndFade,d,function(){f.destroyPointsNotification(g);e.resolve()});return e.promise()},replenishLetter:function(a){var b=this.$board._("withLetter",
a),b=this.letterCount(a)-b.length,c;for(c=0;c<b;c+=1)this.addRandomLetters(a)},postKill:function(a,b){var c=$.Deferred(),d=3*a[0].width()/4,e=0,f=0,g=a.length,h=[],k=0,p=b?-1*g:Math.pow(g-1,2),m=0,l,r,s,u;for(l=a.length-1;0<=l;l--)r=a[l],s=r.offset(),u=r._("letter"),r._("isStationary")&&(m+=1),this.destroyBrick(r),e+=s.left,f+=s.top,""!==u&&h.push(u);e=e/g+d;f=f/g+d;b||(0<h.length&&(k+=Math.pow(h.length+1,2)),0<m&&(k+=Math.pow(m+2,2)),0<k&&(this.addScore(k),this.slideText("+"+k,e+d,f-d)));this.addScore(p);
this.slideText((0<p?"+":"")+p,e,f);for(l="";0<h.length;)if(g=this.word[this.nextLetterIndex],g=h.indexOf(g),-1===g&&(g=h.indexOf(_.asterisk)),-1<g)k=this.markLetterDone(),l+=k,h.splice(g,1);else break;""!==l&&this.slideText(l,e-d,f+d);for(l=h.length-1;0<=l;l--)this.replenishLetter(h[l]);d=a.length-3;if(0<d&&!b)if(this.isWordComplete())if(1===d)this.addRandomWildcard(!1);else for(l=0;l<d-1;l+=1)this.addRandomWildcard(!0);else if(1===d)d=this.word.slice(this.nextLetterIndex),d=d[Math.floor(this.random()*
d.length)],this.addRandomLetters(d);else for(l=0;l<d-1;l+=1)this.addRandomLetters(_.asterisk);c.resolve(1);return c.promise()},wordCompleted:function(){this.$board.find(".l:contains("+_.asterisk+")").each(function(a,b){var c=$(b);c._("letter","");c._("type","t-")})},isLevelCleared:function(){return 0===this.boardCells.find(".k").not(".tr").length},addScore:function(a){this.setScore(this.levelScore+a)},setScore:function(a){this.levelScore=a;$("#score").text(this.levelScore)},setWord:function(a){this.word=
a;var b,c,d=$("#word"),e=a.length;d.empty();for(b=0;b<e;b+=1)c=$("<span>"),c.text(a[b]),b<this.nextLetterIndex&&c.addClass(c.addClass("done-letter")),c.appendTo(d)},isWordComplete:function(){return this.nextLetterIndex>=this.word.length},kill:function(a){var b=this,c=$.Deferred(),d=[];$.each(a,function(a,c){var g=$.Deferred();c.animate(_.A.opacity0,600,function(){b.event("out",c.parent(),c);g.resolve()});d.push(g.promise())});$.when.apply(window,d).then(function(){c.resolve(a)});return c.promise()},
pushOut:function(a){var b,c,d,e,f=this;d=a._("replenishDelta");var g=$.Deferred();e=a._("brick");0<e.length&&d?(b=a._("x"),c=a._("y"),b=this.cell(b+d.x,c+d.y),0<b.length?this.pushOut(b).pipe(function(a){f.move(e,a,0.5)}).pipe(function(){g.resolve(a)}):e.animate(_.A.opacity0,function(){var b=$(this),c=b._("letter");f.destroyBrick(b);""!==c&&f.replenishLetter(c);g.resolve(a)})):g.resolve(a);return g.promise()},handleStopCell:function(a,b){var c=this,d=$.Deferred(),e=b.shift();this.move(a,e).pipe(function(){if(e._("isColorChanger"))return c.changeColor(a);
var b=e._("cellDirection");return b?a._("changeDirection",b):null}).pipe(function(){0<b.length?c.handleStopCell(a,b).done(function(){d.resolve()}):d.resolve()});return d.promise()},shoot:function(a){var b=a.parent(),c=this.findTarget(a),d=$.Deferred();if(c){var e=this,f=c.stops;this.pushOut(c.cell).pipe(function(b){$.Deferred();-1===f.indexOf(b)&&f.push(b);return e.handleStopCell(a,f)}).pipe(function(){var b=a.parent();b.hasClass("r")&&(b=b._("cellDirection"),a._("brickDirection",b))}).pipe(function(){return e.replenish(b)}).pipe(function(){return e.maybeKill(a)}).pipe(function(a){return e.proceed(a)}).done(function(a){d.resolve(a)})}else d.resolve(-1);
return d.promise()},cmpBrickAge:function(a,b){return b.data("age")-a.data("age")},proceed:function(a){var b=$.Deferred(),c=this,d=[],e=a,f,g;f=this.boardCells.find(".k");for(a=f.length-1;0<=a;a--)g=$(f[a]),g._("isStationary")||d.push(g);d.sort(this.cmpBrickAge);var h=function(a){0<a&&(e+=a);k()},k=function(){if(0<d.length){var a=d.shift(),g=a.parent();0<g.length&&g.hasClass("b")?c.shoot(a).done(h):k()}else b.resolve(e)};k();return b.promise()},replenish:function(a){var b=$.Deferred();if(!a.hasClass("r"))return b.resolve(),
b.promise();var c=this,d,e;e=a._("replenishDelta");var f=a._("coord");d=this.cell(f.x+e.x,f.y+e.y);e=d._("brick");0<e.length?this.move(e,a,0.8).done(function(){c.replenish(d).done(function(){b.resolve()})}):this.createBrick(a,null,null,null,null,!0).done(function(){b.resolve()});return b.promise()},shrug:function(a){var b=$.Deferred(),c=function(){b.resolve()};a.rotate({angle:0,animateTo:90,duration:200,callback:function(){a.rotate({animateTo:0,duration:200,callback:c})}});return b.promise()},_brickPool:[],
_populateBrickPool:function(){var a=this.$board._("dimensions").fieldSize,b;for(b=0;b<a*a;b++)this._brickPool.push(this.$board._("newBrick"))},createBrick:function(a,b,c,d,e,f){b=b||this.randomColor();var g=this,h=$.Deferred();d=d||(a.hasClass("r")?a._("cellDirection"):"");var k=this._brickPool.shift()||this.$board._("newBrick");k._("type",b);k._("age",e||null);k._("brickDirection",d);k._("letter",c||"");f?(k.css("opacity",0),a.append(k),k.animate(_.A.opacity1,50,function(){h.resolve();g.event("in",
a,k)})):(a.append(k),h.resolve(),g.event("in",a,k));return h.promise()},destroyBrick:function(a){a.detach();a.css("opacity",1);this._brickPool.push(a)},currentSnapName:function(a){return"l"+a+"cur"},prevSnapName:function(a){return"l"+a+"prev"},takeSnapshot:function(){var a=[],b,c,d,e,f=this.$board.find(".k");for(b=this.boardCells.length-1;0<=b;b--)if(c=$(this.boardCells[b]),e=c.data(),(d=e.modifier)&&!c._("hasBrick"))c=e.coord,a.push([c.x,c.y,d]);var g,h;for(b=f.length-1;0<=b;b--){d=$(f[b]);h=d.data();
c=d.parent();e=c.data();c=e.coord;d=e.modifier;e=h.type;g=h.letter;d=[c.x,c.y,d,e[1],g];if(c=h.direction)d.push(c),(h=h.age)&&d.push(h);a.push(d)}f=this.getLevelId();a={level:f,word:this.word,nextLetterIndex:this.nextLetterIndex,levelScore:this.levelScore,shotCount:this.shotCount,boardState:a,hints:this.hints,seed:this.seed,sequence_pos:this.random_sequence_pos};b=this.currentSnapName(f);f=this.prevSnapName(f);(h=localStorage.getItem(b))&&localStorage.setItem(f,h);localStorage.setItem(b,JSON.stringify(a));
this.updateUndoButton()},restorePrevious:function(){var a=this.getLevelId(),b=this.currentSnapName(a),a=this.prevSnapName(a);localStorage.getItem(b);var c=localStorage.getItem(a);if(c)return localStorage.removeItem(b),localStorage.removeItem(a),localStorage.setItem(b,c),this.loadSnapshot(c);b=$.Deferred();b.reject();return b.promise()},hasPrevious:function(){var a=this.getLevelId(),a=this.prevSnapName(a);return localStorage.getItem(a)?!0:!1},loadSnapshot:function(a){this.clearBoard();a=JSON.parse(a);
this.setSeed(a.seed,a.sequence_pos);this.setScore(a.levelScore);this.shotCount=a.shotCount;this.nextLetterIndex=a.nextLetterIndex;this.setWord(a.word);this.levelSelector.setCurrentLevelId(a.level);var b=a.boardState;this.updateUndoButton();this.loadHints(a.hints);return this.loadBricks(b)},deleteSnapshots:function(){var a=this.getLevelId(),b=this.currentSnapName(a),a=this.prevSnapName(a);localStorage.removeItem(b);localStorage.removeItem(a);this.updateUndoButton()},deleteHints:function(){this.hints.length=
0;$(".hint").filter(":not([id])").remove()},clearState:function(){this.deleteSnapshots();this.deleteHints();this.clearCellModifiers()},setHighScore:function(a){this.highScore=a;$("#highScore").text(this.highScore)},saveHighScore:function(){var a=this.getLevelId();return this.levelScore>this.highScore?(this.setHighScore(this.levelScore),localStorage.setItem("l"+a+"highScore",this.highScore),!0):!1},restoreHighScore:function(){var a=this.getLevelId(),a=localStorage.getItem("l"+a+"highScore");this.setHighScore(parseInt(a)||
0)},updateUndoButton:function(){var a=$("#undoMove"),b=$("#resetLevel");this.hasPrevious()?b.is(":visible")&&(b.hide(),a.show()):a.is(":visible")&&(a.hide(),b.show())},resetLevel:function(){this.clearState();return this.setLevelId(this.getLevelId())},nextLevel:function(){this.setLevelId(this.levelSelector.getNextLevelId())},prevLevel:function(){this.setLevelId(this.levelSelector.getPrevLevelId())},isLastLevel:function(){return this.levelSelector.isLastLevel()},setLevelId:function(a){var b=this;a=
this.levelSelector.setCurrentLevelId(a);var c=this.levelSelector.getCurrentLevelIndex();$("#levelLabel").text(c+1);this.deleteHints();this.clearCellModifiers();return this.showMessage("Loading...",_.A.opacity0,300,function(){return b.populate(a).done(function(){b.event("levelLoaded")})})},center:function(a){var b=a.offset();a=a.width()/2;return{x:b.left+a,y:b.top+a}},calcLevelBonus:function(){var a=96+Math.min(4*this.shotCount,900),b=this.$board.find(".tb"),c=Math.pow(b.length+2,2),d=c*b.length,e=
this.$board.find(".t-"),f=Math.pow(e.length+1,2),g=f*e.length,h=this.$board.find(".tr"),k=Math.pow(h.length+6,2),p=k*h.length,m,l;for(m=b.length-1;0<=m;m--)l=$(b[m]),l=this.center(l),this.slideText("+"+c,l.x,l.y);for(m=e.length-1;0<=m;m--)l=$(e[m]),l=this.center(l),this.slideText("+"+f,l.x,l.y);for(m=h.length-1;0<=m;m--)l=$(h[m]),l=this.center(l),this.slideText("+"+k,l.x,l.y);return a+d+g+p},blockUI:function(){this.busy=!0},unblockUI:function(){this.busy=!1},updateHintPositions:function(){$(".hint").filter(".updateHintPos").each(function(){var a=
$(this),b=a.data("setPos");b||console.warn("not set pos",a);b()})},setup:function(){var a=this,b=function(b){a.updateHintPositions()};$(window).on("resize",b);var c=function(a){$("#overlay").find(".overlayWidget:visible").hide();$(".uiHint").hide();$("#overlay").hide();$("#transparentOverlay").hide()},d=function(b){if(!a.busy){var c=$("#transparentOverlay"),d=$("#overlay");b=$("#"+b);c.show();d.show();b.show()}},e=function(){d("levelsContainer")};a.levelSelector.onLevelSelected=function(b){c();a.setLevelId(b.id)};
var f=function(){d("confirmResetContainer")};$("#confirmResetYes").on(this.buttonEvent,function(){c();a.resetLevel()});$("#confirmResetNo").on(this.buttonEvent,function(){c()});$("#resetLevel").on(this.buttonEvent,f);var g=function(){!a.busy&&a.hasPrevious()&&a.showMessage("Loading...",_.A.opacity0,300,function(){return a.restorePrevious().done(function(){a.event("levelLoaded")})})};$("#undoMove").on(this.buttonEvent,g);var h=function(b,c,d){var g=$("#"+b),e=$("#"+c);g.data("setPos",function(){a.position(g,
d?a.calcPositionTop(e,g):a.calcPositionBottom(e,g),g)})};h("hintLevelButton","levelLabelContainer",!1);h("hintUndoButton","undoButtonContainer",!0);h("hintScore","score",!0);h("hintShowInfo","showInfoContainer",!0);h=function(){a.busy||(b(),$(".uiHint").show(),d("rulesContainer"))};$("#showHowToPlay").on(this.buttonEvent,h);var k={27:c,s82:f,78:function(){c();a.nextLevel()},80:function(){c();a.prevLevel()},37:function(){$("#selectLevelWidget").is(":visible")&&a.levelSelector.pageLeft()},39:function(){$("#selectLevelWidget").is(":visible")&&
a.levelSelector.pageRight()},76:e,72:h,s191:h,8:g};$("body").keyup(function(a){(a=k[(a.shiftKey?"s":"")+(a.ctrlKey?"c":"")+(a.metaKey?"m":"")+a.keyCode])&&a()});$(".closeButton").on(this.buttonEvent,c);$("#selectLevel").on(this.buttonEvent,e);this._populateBrickPool();this.repoEdgeCells.on(this.shootEvent,function(){if(!a.busy){var b=$(this)._("brick");0<b.length&&(a.blockUI(),a.shoot(b).pipe(function(c){var d=$.Deferred();-1===c?a.shrug(b).then(function(){a.unblockUI();d.reject()}):d.resolve(c);
return d.promise()}).pipe(function(b){var c=$.Deferred(),d=a.isLevelCleared();a.shotCount+=1;if(1<b){var g,e,f,h=Math.pow(b+1,2),k;for(g=0;g<b-1;g++)if(f=a.addRandomWildcard(!0,"tb"))a.addScore(h),e=a.center(f),d?(k=f.width()/2,f=e.x+k,e=e.y-k):(f=e.x,e=e.y),a.slideText("+"+h,f,e)}d?c.resolve():(a.takeSnapshot(),a.unblockUI(),c.reject());return c.promise()}).pipe(function(){var b=$.Deferred();a.event("levelCleared");a.clearState();if(a.isWordComplete()){var c=a.calcLevelBonus();a.addScore(c);if(a.saveHighScore()){var d=
$("#hintTop").clone().attr("id",null);d.find(".hint-text").text("High score!");setTimeout(function(){d.appendTo($("body"));a.position(d,a.calcPositionTop($("#score"),d));d.show()},20)}a.slideMessage("Solved! +"+c).done(function(){d&&d.animate(_.A.opacity0,500,function(){d.remove()});a.isLastLevel()?a.slideMessage("No more levels").done(function(){b.resolve()}):b.resolve()})}else a.slideMessage("Word is not complete, try again").done(function(){a.unblockUI();b.reject();a.resetLevel()});return b.promise()}).pipe(function(){a.unblockUI();
a.nextLevel()}))}})},slideMessage:function(a){return this.showMessage(a,_.A.slideUpAndFade,2E3)},_infoNotificationPool:[],createInfoNotification:function(){var a=this._infoNotificationPool.shift()||$("<p>").addClass("info-notification").addClass("accel");a.css("opacity",1);return a},destroyInfoNotification:function(a){a.detach();this._infoNotificationPool.push(a)},showMessage:function(a,b,c,d){var e=this.$board,f=this;e.offset();e.width();e.height();var g=$("#overlay");f.blockUI();g.show();var h=
this.createInfoNotification();h.text(a).appendTo($("#overlayContent"));var k=$.Deferred(),p=function(a){h.animate(b,c,function(){f.destroyInfoNotification(h);g.hide();f.unblockUI();k.resolve(a)})};d?setTimeout(function(){d().always(p)},20):p();return k.promise()},loadBricks:function(a){var b=this.$board,c=b.parent(),d=this,e=$.Deferred(),f=[];b.detach();$.each(a,function(a,b){var c=b[0],e=b[1],m=b[2],l=b[3],r=b[4],s=b[5],u=b[6];"*"===r&&(r=_.asterisk);m&&d.cell(c,e)._("mark",m);l&&(l="?"===l?d.randomColor():
"t"+l,f.push(d.createBrick(d.cell(c,e),l,r,s,u)))});$.when.apply(window,f).then(function(){c.append(b);e.resolve()});return e.promise()},loadWord:function(a){var b=$.Deferred();a||(a="");this.setWord(a.toUpperCase());for(a=this.word.length-1;0<=a;a--)this.replenishLetter(this.word[a]);b.resolve();return b.promise()},hints:[],loadHints:function(a){var b,c,d,e=$.Deferred();this.deleteHints();for(b=a.length-1;0<=b;b--)c=a[b],d={},$.extend(!0,d,c),(c=this.createHint(d))&&this.hints.push(d);e.resolve();
return e.promise()},calcPositionRight:function(a,b){var c=a.offset(),d=c.top+(a.height()-b.height())/2,c=c.left+a.width();return{top:d,left:c}},calcPositionLeft:function(a,b){var c=a.offset(),d=c.top+(a.height()-b.height())/2,c=c.left-b.width();return{top:d,left:c}},calcPositionTop:function(a,b){(!a||0===a.length)&&console.log("- Can't position ",b);(!b||0===b.length)&&console.log("* Can't position ",b);var c=a.offset(),d=c.top-b.height(),c=c.left+(a.width()-b.width())/2;return{top:d,left:c}},calcPositionBottom:function(a,
b){var c=a.offset(),d=c.top+a.height(),c=c.left+(a.width()-b.width())/2;return{top:d,left:c}},position:function(a,b){var c=a.offset();(2<Math.abs(c.top-b.top)||2<Math.abs(c.left-b.left))&&a.css(b)},calcLevelHintPosition:function(a){var b=this.$board._("dimensions"),c=this.cell(b.repoSize,0),d=this.cell(b.fieldSize+b.repoSize,b.repoSize),b=c.width()*b.fieldSize;a.width()>b&&a.width(b);c=c.offset();b=d.offset();d=(c.left+b.left)/2;c=(c.top+b.top)/2-a.height()/2;a=d-a.width()/2;return{top:c,left:a}},
createHint:function(a){var b=this,c,d,e,f=this.$board;if(a.hide.fired)return!1;var g=function(g){var f;"top"===a.show.where?(f=$("#levelHintContainer").clone().addClass("updateHintPos").addClass("accel").attr("id",null),f.find(".hint-text").text(a.text),g=function(){b.position(f,b.calcLevelHintPosition(f))}):"word"===a.show.where?(f=$("#hintBottom").clone().addClass("updateHintPos").addClass("accel").attr("id",null),f.find(".hint-text").text(a.text),g=function(){var a=$("#word"),a=a.is(":visible")?
b.calcPositionBottom(a,f):{top:0,left:-f.width()};b.position(f,a)}):(c=b.cell(g[0],g[1]),c.hasClass("ru")?(d="#hintBottom",e=b.calcPositionBottom):c.hasClass("rl")?(d="#hintLeft",e=b.calcPositionRight):c.hasClass("rr")?(d="#hintRight",e=b.calcPositionLeft):(d="#hintTop",e=b.calcPositionTop),f=$(d).clone().addClass("updateHintPos").attr("id",null),f.find(".hint-text").text(a.text),g=function(){b.position(f,e(c,f))});f.data("setPos",g);f.appendTo($("body"));return f},h=function(a,b){if(!b)return!1;
var c=!1;$.each(b,function(b,d){d[0]===a[0]&&d[1]===a[1]&&(c=!0);return!c});return c},k=function(a,b,c){return function(d,g){if({levelLoaded:1,levelCleared:1}[d.type])return!0;var e=g.cell._("x"),f=g.cell._("y"),e=g.cell&&0<g.cell.length&&(!a||e===a[0]&&f===a[1]&&!h([e,f],g.excludedCells)),f=!b||g.brickType&&g.brickType===b,k=!c||g.letter&&(g.letter===c||g.letter===_.asterisk&&"*"===c);return e&&f&&k}},p=a.show.event,m=a.hide.event,l=k(p.cell,p.brickType,p.letter),r=k(m.cell,m.brickType,m.letter),
s=function(b){var c,d,e;a.show.fired=!0;a.show.cell?c=a.show.cell:a.show.event.cell?c=a.show.event.cell:b&&(b.cell&&0<b.cell.length)&&(c=[b.cell._("x"),b.cell._("y")],a.show.event.cell=c);d=g(c);e=d.data("setPos");f.unbind(p.type,u);f.bind(m.type,function(b,c){r(b,c)&&(a.hide.fired=!0,d.animate(_.A.opacity0,500,function(){d.remove()}))});setTimeout(function(){e();d.show()},50)},u=function(a,b){l(a,b)&&s(b)};a.show.fired?s():this.$board.bind(p.type,u);return!0},addRandomLetters:function(a){var b,c,
d=$.Deferred(),e=a.length,f=this.repoCells,g=function(a){return!a._("brick")._("letter")};for(b=0;b<e;b+=1)c=this.randomCell(f,g),c=c._("brick"),c._("letter",a[b]);d.resolve();return d.promise()},addRandomWildcard:function(a,b){var c,d=this,e=b||"t-";c=a?this.repoEdgeCells.filter(function(){var a=$(this)._("brick");return null!==d.findTarget(a)}):this.repoCells;c=this.randomCell(c,function(a){a=a._("brick");return!a.hasClass(e)&&!a.hasClass("t-")&&0<a.length});return 0<c.length?(c=c._("brick"),c._("type",
e),c):a?this.addRandomWildcard(!a,e):null},clearBoard:function(){var a=this;$(".k").each(function(){a.destroyBrick($(this))})},loadLevel:function(a){var b=this;this.clearBoard();var c=$.Deferred();a=this.levelSelector.getLevel(a);this.setScore(0);this.nextLetterIndex=this.shotCount=0;this.loadHints(a.hints);a=[this.loadBricks(a.layout),this.loadWord(a.word)];$.when.apply(window,a).then(function(){b.setSeed();b.takeSnapshot();c.resolve()});return c.promise()},populate:function(a){var b=this.currentSnapName(a),
b=localStorage.getItem(b);this.restoreHighScore();if(b)try{return this.loadSnapshot(b)}catch(c){return console.log("Failed to load snapshot for level "+a,c),this.loadLevel(a)}else return this.loadLevel(a)},levelScore:0,hishScore:0,shotCount:0,getLevelId:function(){return this.levelSelector.getCurrentLevelId()},setStyle:function(a){$("link").each(function(){var b=$(this),c=b.attr("title");c&&(c===a?(b.attr("rel","stylesheet"),b.attr("disabled",!1)):(b.attr("rel","alternate stylesheet"),b.attr("disabled",
!0)))})},parseOptions:function(a){var b=window.location.hash.substring(1).split(";");$.each(b,function(b,d){var e=d.split("=",2);1===e.length?e[0]&&(a[e[0]]=!0):2===e.length&&e[0]&&({no:1,"false":1,0:1}[e[1].toLowerCase()]?a[e[0]]=!1:a[e[0]]=e[1])});return a},levelSelector:{onLevelSelected:function(a){console.log("Level selected: "+a.id)},create:function(a,b,c){function d(a,b,c,d){if(!a)return $("<div>").addClass("levelThumb").addClass("toolButton");c=a?a.id:null;a=$(a.thumb);a.data("levelId",c);
a.data("levelIndex",b);return a}function e(){s(m-1)}function f(){s(m+1)}function g(b){var c=h[b];console.log("Level index for ",b,"is",c);c?(k=b,p=c):(p=0,k=a.levels[p].id);localStorage.setItem("level",k);s(Math.floor(c/l));return k}var h={};$.each(a.levels,function(a,b){h[b.id]=a});var k=null,p,m,l=9;this.pageLeft=e;this.pageRight=f;this.setCurrentLevelId=g;var r=function(){if(null===k){var a=localStorage.getItem("level");return g(a)}return k};this.getCurrentLevelId=r;this.getCurrentLevelIndex=function(){return p};
this.getNextLevelId=function(){var b=h[r()];return(b=a.levels[b+1])?b.id:a.levels[0].id};this.isLastLevel=function(){var b=h[r()];return!a.levels[b+1]};this.getPrevLevelId=function(){var b=h[r()];return(b=a.levels[b-1])?b.id:a.levels[a.levels.length-1].id};this.getLevel=function(b){return a.levels[h[b]]};var s=function(a){0>a?a=u-1:a>=u&&(a=0);var b=a*l,c=b+l;m=a;var d=1,g,e;for($("#selectLevelWidget").find(".thumbHolder").find(".levelThumb").detach();b<c;b++)g=n[b],g.removeClass("levelThumbCurrent"),
b===p&&g.addClass("levelThumbCurrent"),e=localStorage.getItem("l"+g.data("levelId")+"highScore"),g.find(".thumb-highScore").text(parseInt(e)||0),e=$("#thumbHolder"+d),e.append(g),d+=1;$("#pagePositionContainer").find("div.activePagePosition").removeClass("activePagePosition");$("#pagePositionIndicator"+a).addClass("activePagePosition")},u=function(){var b=Math.ceil(a.levels.length/l),c=$("#pagePositionContainer"),d;for(d=0;d<b;d++)$("<div>").attr("id","pagePositionIndicator"+d).addClass("pagePositionIndicator").appendTo(c).on(_.buttonEvent,
function(a){return function(){s(a)}}(d));return b}(),n=function(){var b,c=a.levels,g=c.length,e,f={};console.log("Levels count:",g);for(b=0;b<g;b++)e=d(c[b],b),f[b]=e;for(;b<u*l;)e=d(c[b]),f[b]=e,b+=1;return f}(),w=this;$("#btnScrollLevelsLeft").on(_.buttonEvent,function(){e()});$("#btnScrollLevelsRight").on(_.buttonEvent,function(){f()});$("#selectLevelWidget").delegate(".thumb-board",_.buttonEvent,function(){var b=$(this).parent().data("levelIndex");w.onLevelSelected(a.levels[b])})}},allHintsFired:function(){var a=
!0;if(0===this.hints.length)return!0;$.each(this.hints,function(b,c){return c.hide.fired?!0:a=!1});return a},event:function(a,b,c,d){this.allHintsFired()||this.$board.trigger(a,{cell:b,brickType:c?c._("type"):void 0,letter:d})},main:function(a,b){this.setSeed();var c=window.devicePixelRatio||1;1!==c&&$("head").append('<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale='+1/c+'"/>');c={asterisk:"\u2217"};navigator&&navigator.userAgent&&-1<navigator.userAgent.indexOf("hpwOS")&&
(c.asterisk="*");Modernizr.touch?(console.log("Touch events are supported"),this.buttonEvent="touchend",this.shootEvent="touchstart",$("#keyboardShortcutsInfo").hide(),$(function(){var a=$("#rulesContainer");$(document).bind("touchmove",function(b){a.is(":visible")||b.preventDefault()})})):(console.log("Touch events are NOT supported"),this.shootEvent=this.buttonEvent="click");c=this.parseOptions(c);console.log("Options: "+c);this.asterisk=c.asterisk;this.$board=$("#board")._("init",a,b);this.repoEdgeCells=
this.$board.find(".re");this.repoCells=this.$board.find(".r");this.boardCells=this.$board.find(".b");var d=this;this.showMessage("Preparing...",_.A.opacity0,0,function(){var c=$.Deferred();d.setup();$.getJSON("levels.json",function(f){d.levels=f.levels;var g=f.appDisplayName;g&&$("#rulesAppName").text(g);var h=f.nag;h&&h.message&&($("#nagText").text(h.message),$("#rulesNag").text(h.message),$("#nagContainer").show(),$("#rulesNagContainer").show(),h.url&&($("#rulesNag").attr("href",h.url),$("#nagText").on(d.buttonEvent,
function(){window.open(h.url)})));d.levelSelector.create(f,a,b);f=d.levelSelector.getCurrentLevelId();c.resolve(f)});return c.promise()}).pipe(function(a){d.setLevelId(a).done(function(){d.$board.animate(_.A.opacity1,500);$("#levelLabelContainer").show();$("#scoreContainer").show();$("#showInfoContainer").show();$("#undoButtonContainer").show();d.updateUndoButton();d.updateHintPositions()})})}};
(function(a){var b={rd:"du",ru:"dd",rr:"dl",rl:"dr"},c={dl:{x:-1,y:0},dr:{x:1,y:0},du:{x:0,y:-1},dd:{x:0,y:1},d0:{x:0,y:0}},d={rd:{x:0,y:1},ru:{x:0,y:-1},rr:{x:1,y:0},rl:{x:-1,y:0}},e={top:"",left:""},f={_default:function(){return a("#board")},newBrick:function(){return a("<div/>").addClass("k").addClass("accel").append(a("<div/>").addClass("quad-content"))},type:function(a){if(void 0!==a){var b=this.data("type"),c=this.parent();b&&this.removeClass(b);this.addClass(a);this.data("type",a);c&&_.event("in",
c,this)}return this.data("type")},age:function(a){void 0!==a&&this.data("age",a);return this.data("age")},isUnchangeableType:function(){var a=this.data("type")[1];return"-"===a||"b"===a||"r"===a},content:function(){return this.children(":first")},brickDirection:function(a){var b=this._("content");if(void 0!==a){var c=this.data("direction");c&&b.removeClass(c);b.addClass(a);this.data("direction",a)}return this.data("direction")},changeDirection:function(b){var d=a.Deferred(),e=this,f=function(){e._("brickDirection",
b);e.rotate({angle:0,animateTo:0,duration:0});d.resolve()},m=this._("delta"),l=c[b],m=90*(m.x*l.y-m.y*l.x+m.x*l.x*(1-m.x*l.x)+m.y*l.y*(1-m.y*l.y));0===m?d.resolve():this.rotate({angle:0,animateTo:m,duration:200,callback:f});return d.promise()},isStationary:function(){return!this._("brickDirection")},letter:function(a){if(void 0===a)return this.data("letter");var b=this.parent();this._("content").text(a);this.data("letter",a);a?(this.addClass("l"),_.event("in",b,this,a)):(this.removeClass("l"),_.event("out",
b,this,a));return a},delta:function(){var a=this._("brickDirection");return c[a]||c.d0},resetTopLeft:function(){this.css(e)},isColorChanger:function(){return"cc"===this.data("modifier")},modifier:function(){return this.data("modifier")},coord:function(){return this.data("coord")},x:function(){var a=this.data("coord");return a?a.x:void 0},y:function(){var a=this.data("coord");return a?a.y:void 0},brick:function(){return this.children(":first")},hasBrick:function(a){return 0===this._("brick").length?
!1:!0},mark:function(a){this.addClass(a).data("modifier",a)},cellDirection:function(){return b[this.data("modifier")]||""},cellDirectionDelta:function(){var a=this._("cellDirection");return a?c[a]:null},replenishDelta:function(){return d[this.data("modifier")]||null},init:function(b,c){var d=b+c,e=2*b+c,f=[],l=a("#board"),r,s,u,n,w;for(r=0;r<e;r++){u=a("<tr/>");w=[];for(s=0;s<e;s++){n=s;var q=r,t=[],x=void 0,v=a("<td/>").data("coord",{x:n,y:q});n>=b&&n<d&&q>=b&&q<d?(t.push("b"),((n===b||n===d-1)&&
q>=b&&q<d||(q===b||q===d-1)&&n>=b&&n<d)&&t.push("be")):(((n===b-1||n===d)&&q>b-1&&q<d||(q===b-1||q===d)&&n>b-1&&n<d)&&t.push("re"),n>=b&&(n<d&&q<b&&0<=q)&&(t.push("r"),t.push("ru"),v.data("modifier","ru"),x=!0),n>=b&&(n<d&&q>=d&&q<e)&&(t.push("r"),t.push("rd"),v.data("modifier","rd"),x=!0),n<b&&(0<=n&&q>=b&&q<d)&&(t.push("r"),t.push("rl"),v.data("modifier","rl"),x=!0),n>=d&&(n<e&&q>=b&&q<d)&&(t.push("r"),t.push("rr"),v.data("modifier","rr"),x=!0),x||t.push("x"),0<=n&&n<b&&0<=q&&q<b?t.push("tlc"):
n>=d&&n<e&&0<=q&&q<b?t.push("trc"):0<=n&&n<b&&q>=d&&q<e?t.push("blc"):n>=d&&(n<e&&q>=d&&q<e)&&t.push("brc"));v.addClass(t.join(" "));n=v;n.appendTo(u);w.push(n)}u.appendTo(l);f.push(w)}a(".tlc").slice(1).remove();a(".tlc").attr({colspan:b,rowspan:b}).append(a("#levelLabelContainer"));a(".trc").slice(1).remove();a(".trc").attr({colspan:b,rowspan:b}).append(a("#scoreContainer"));a(".brc").slice(1).remove();a(".brc").attr({colspan:b,rowspan:b}).append(a("#showInfoContainer"));a(".blc").slice(1).remove();
a(".blc").attr({colspan:b,rowspan:b}).append(a("#undoButtonContainer"));this.data("dimensions",{repoSize:b,fieldSize:c});this.data("cells",f);return this},cell:function(b,c){var d=this.data("cells")[c];if(!d)return a();d=d[b];return!d?a():d},dimensions:function(){return this.data("dimensions")},withLetter:function(a){return this.find(".l:contains("+a+")")}};a.fn._=function(b){if(f[b])return f[b].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof b||!b)return f._default.apply(this,
arguments);a.error("Method "+b+" does not exist on jQuery._")}})(jQuery);$(function(){_.main(3,10)});
